'use client';

import React, { useState, useTransition } from 'react';
import { BrainCircuitRegular } from '@fluentui/react-icons';
import { generateQuestion } from '@/actions/conceptforge';
import { CF_TOPICS } from '@/data/conceptForgeDemo';

const PROVIDERS = [
  { id: 'claude', label: 'Claude', env: 'ANTHROPIC_API_KEY' },
  { id: 'groq', label: 'GROQ', env: 'GROQ_API_KEY' },
];

const ERRORS = {
  empty: 'Pick or type a topic first.',
  too_long: 'Keep it under 240 characters.',
  refused: 'The model declined that request. Try a JEE topic.',
  busy: 'The model is busy right now — give it a few seconds and try again.',
  failed: 'Something went wrong. Try again.',
};

export default function ConceptForgeDemo() {
  const [q, setQ] = useState('');
  const [provider, setProvider] = useState('claude');
  const [result, setResult] = useState(null);
  const [picked, setPicked] = useState(null);
  const [pending, startTransition] = useTransition();

  const active = PROVIDERS.find((p) => p.id === provider);
  const errorText = (code) =>
    code === 'unconfigured'
      ? `Live demo is offline — set ${active.env} to enable ${active.label}.`
      : ERRORS[code] || ERRORS.failed;

  const run = (text) => {
    const topic = (text ?? q).trim();
    if (!topic || pending) return;
    if (text != null) setQ(text);
    setResult(null);
    setPicked(null);
    startTransition(async () => setResult(await generateQuestion(topic, provider)));
  };

  const selectProvider = (id) => {
    if (id === provider || pending) return;
    setProvider(id);
    setResult(null);
    setPicked(null);
  };

  const revealed = picked != null;

  return (
    <div className="demo-widget">
      <div className="demo-head">
        <span className="demo-badge"><BrainCircuitRegular style={{ fontSize: 13 }} /> Live · Adaptive Engine</span>
        <span className="demo-sub">Pick a topic — get a JEE question, generated by {active.label}.</span>
      </div>

      <div className="demo-providers" role="group" aria-label="Model provider">
        {PROVIDERS.map((p) => (
          <button
            key={p.id}
            type="button"
            className={`demo-provider${p.id === provider ? ' is-active' : ''}`}
            aria-pressed={p.id === provider}
            onClick={() => selectProvider(p.id)}
            disabled={pending}
          >
            {p.label}
          </button>
        ))}
      </div>

      <form className="demo-input" onSubmit={(e) => { e.preventDefault(); run(); }}>
        <BrainCircuitRegular style={{ fontSize: 15, flexShrink: 0, opacity: 0.6 }} />
        <input
          value={q}
          onChange={(e) => setQ(e.target.value)}
          placeholder="e.g. Rotational Dynamics"
          maxLength={240}
          aria-label="JEE topic"
        />
        <button type="submit" disabled={pending || !q.trim()}>{pending ? '…' : 'Generate'}</button>
      </form>

      <div className="demo-examples">
        {CF_TOPICS.map((t) => (
          <button key={t} type="button" className="demo-chip" onClick={() => run(t)} disabled={pending}>{t}</button>
        ))}
      </div>

      <div className="demo-output">
        {pending && <div className="demo-status">Generating a question with {active.label}…</div>}
        {!pending && result?.error && <div className="demo-status demo-error">{errorText(result.error)}</div>}
        {!pending && result?.ok === false && <div className="demo-status">{result.note}</div>}
        {!pending && result?.ok && (
          <div className="cf-quiz">
            <p className="cf-question">{result.question}</p>
            <div className="cf-options">
              {result.options.map((opt, i) => {
                const isAnswer = i === result.answerIndex;
                let cls = 'cf-option';
                if (revealed && isAnswer) cls += ' correct';
                else if (revealed && i === picked) cls += ' wrong';
                return (
                  <button
                    key={i}
                    className={cls}
                    disabled={revealed}
                    onClick={() => setPicked(i)}
                  >
                    <span className="cf-opt-key">{String.fromCharCode(65 + i)}</span>
                    <span>{opt}</span>
                  </button>
                );
              })}
            </div>
            {revealed && (
              <div className="cf-reveal">
                <p className="cf-verdict">{picked === result.answerIndex ? '✓ Correct' : '✗ Not quite'}</p>
                <p className="cf-solution">{result.solution}</p>
                <div className="cf-prereq">
                  <span className="cf-prereq-label">Prerequisite</span>
                  <span className="cf-prereq-name">{result.prerequisite}</span>
                </div>
              </div>
            )}
          </div>
        )}
        {!pending && !result && (
          <p className="demo-hint">Mastery scoring · prerequisite DAG · adaptive difficulty — try one.</p>
        )}
      </div>
    </div>
  );
}
