'use client';

import React, { useState, useTransition } from 'react';
import { SearchRegular, DatabaseRegular } from '@fluentui/react-icons';
import { generateSql } from '@/actions/nlsql';
import { DEMO_SCHEMA, DEMO_EXAMPLES } from '@/data/nlsqlDemo';

const PROVIDERS = [
  { id: 'claude', label: 'Claude', env: 'ANTHROPIC_API_KEY' },
  { id: 'groq', label: 'GROQ', env: 'GROQ_API_KEY' },
];

const ERRORS = {
  empty: 'Type a question first.',
  too_long: 'Keep it under 240 characters.',
  refused: 'The model declined that request. Try a data question.',
  busy: 'The model is busy right now — give it a few seconds and try again.',
  failed: 'Something went wrong generating the query. Try again.',
};

export default function NlSqlDemo() {
  const [q, setQ] = useState('');
  const [provider, setProvider] = useState('claude');
  const [result, setResult] = useState(null);
  const [pending, startTransition] = useTransition();

  const active = PROVIDERS.find((p) => p.id === provider);

  const errorText = (code) =>
    code === 'unconfigured'
      ? `Live demo is offline — set ${active.env} to enable ${active.label}.`
      : ERRORS[code] || ERRORS.failed;

  const run = (questionText) => {
    const question = (questionText ?? q).trim();
    if (!question || pending) return;
    if (questionText != null) setQ(questionText);
    setResult(null);
    startTransition(async () => {
      const res = await generateSql(question, provider);
      setResult(res);
    });
  };

  const selectProvider = (id) => {
    if (id === provider || pending) return;
    setProvider(id);
    setResult(null);
  };

  return (
    <div className="demo-widget">
      <div className="demo-head">
        <span className="demo-badge"><DatabaseRegular style={{ fontSize: 13 }} /> Live · NL → SQL</span>
        <span className="demo-sub">Ask in plain English. Real SQL, generated by {active.label}.</span>
      </div>

      <div className="demo-providers" role="group" aria-label="Model provider">
        {PROVIDERS.map((p) => (
          <button
            key={p.id}
            type="button"
            className={`demo-provider${p.id === provider ? ' is-active' : ''}`}
            aria-pressed={p.id === provider}
            onClick={() => selectProvider(p.id)}
            disabled={pending}
          >
            {p.label}
          </button>
        ))}
      </div>

      <form
        className="demo-input"
        onSubmit={(e) => { e.preventDefault(); run(); }}
      >
        <SearchRegular style={{ fontSize: 15, flexShrink: 0, opacity: 0.6 }} />
        <input
          value={q}
          onChange={(e) => setQ(e.target.value)}
          placeholder="e.g. Top 5 customers by revenue"
          maxLength={240}
          aria-label="Ask a question about the demo database"
        />
        <button type="submit" disabled={pending || !q.trim()}>
          {pending ? '…' : 'Run'}
        </button>
      </form>

      <div className="demo-examples">
        {DEMO_EXAMPLES.map((ex) => (
          <button key={ex} type="button" className="demo-chip" onClick={() => run(ex)} disabled={pending}>
            {ex}
          </button>
        ))}
      </div>

      <div className="demo-output">
        {pending && <div className="demo-status">Generating query with {active.label}…</div>}

        {!pending && result?.error && (
          <div className="demo-status demo-error">{errorText(result.error)}</div>
        )}

        {!pending && result?.ok === false && (
          <div className="demo-status">{result.explanation}</div>
        )}

        {!pending && result?.ok && (
          <>
            <pre className="nlsql-sql"><code>{result.sql}</code></pre>
            <p className="nlsql-explain">{result.explanation}</p>
            {result.tablesUsed?.length > 0 && (
              <div className="nlsql-tables">
                {result.tablesUsed.map((t) => <span key={t}>{t}</span>)}
              </div>
            )}
          </>
        )}

        {!pending && !result && (
          <details className="nlsql-schema">
            <summary>Demo schema</summary>
            <pre><code>{DEMO_SCHEMA}</code></pre>
          </details>
        )}
      </div>
    </div>
  );
}
